# Assignment 1
### Carlos Dasaed Salcedo Carreno
### cdsalcedo@mun.ca
### 201892008


## Question 1:

A) Generate a 1D NumPy array nparray1D containing numbers from -10 to 10 in
increments of 0.2.

B) Make another 2D NumPy array 5x11 called nparray2D containing even numbers
equally spaced values between 2 and 112.

C) Write a function called k_sum which takes input parameters k and N and returns the
partial sum  from n=2 to N, sum 2/( (n^k) +1)
 Don't use loops.

D) A magic square is a matrix all of whose row sums, column sums and the sums of the
two diagonals are the same. (One diagonal of a matrix goes from the top left to the
bottom right, the other diagonal goes from top right to bottom left.). Define function to
verify that the matrix is a magic square or not. Hints: The function np.diag extracts
the diagonal of a matrix, and the function np.fliplr extracts the other diagonal. Don’t
use loops.

In [7]:
import numpy as np

print("Part A")
a = np.arange(-10,10,0.2)
print(a)


Part A
[-1.00000000e+01 -9.80000000e+00 -9.60000000e+00 -9.40000000e+00
 -9.20000000e+00 -9.00000000e+00 -8.80000000e+00 -8.60000000e+00
 -8.40000000e+00 -8.20000000e+00 -8.00000000e+00 -7.80000000e+00
 -7.60000000e+00 -7.40000000e+00 -7.20000000e+00 -7.00000000e+00
 -6.80000000e+00 -6.60000000e+00 -6.40000000e+00 -6.20000000e+00
 -6.00000000e+00 -5.80000000e+00 -5.60000000e+00 -5.40000000e+00
 -5.20000000e+00 -5.00000000e+00 -4.80000000e+00 -4.60000000e+00
 -4.40000000e+00 -4.20000000e+00 -4.00000000e+00 -3.80000000e+00
 -3.60000000e+00 -3.40000000e+00 -3.20000000e+00 -3.00000000e+00
 -2.80000000e+00 -2.60000000e+00 -2.40000000e+00 -2.20000000e+00
 -2.00000000e+00 -1.80000000e+00 -1.60000000e+00 -1.40000000e+00
 -1.20000000e+00 -1.00000000e+00 -8.00000000e-01 -6.00000000e-01
 -4.00000000e-01 -2.00000000e-01 -3.55271368e-14  2.00000000e-01
  4.00000000e-01  6.00000000e-01  8.00000000e-01  1.00000000e+00
  1.20000000e+00  1.40000000e+00  1.60000000e+00  1.80000000e+00
  2.00000000e+00  

In [11]:
import numpy as np
print("Part B")
nparray2d = np.arange(2,112,2).reshape(5,11)
print(nparray2d)


Part B
[[  2   4   6   8  10  12  14  16  18  20  22]
 [ 24  26  28  30  32  34  36  38  40  42  44]
 [ 46  48  50  52  54  56  58  60  62  64  66]
 [ 68  70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108 110]]


In [38]:
import numpy as np
print("Part C")

def k_sum(k, N):
    return  np.sum(2 / ((np.arange(2,N)^k) +1))
    #kval = np.arange(2,n,dtype=float)
    #kval2 = np.fromfunction(lambda x: 2/( (x^k) +1), (1,n), dtype=float)
    #sum 2/( (n^k) +1)

print(k_sum(3,20))


Part C
6.028812647620697


In [69]:
import numpy as np
print("Part D")
def magicsquare(matrix):
    rows = np.sum(matrix,axis=0)
    cols = np.sum(matrix,axis=1)
    diag1 = np.sum(np.diag(matrix))
    diag2 = np.sum(np.diag(np.fliplr(matrix)))
    return ((diag1==diag2) and (diag1==rows[0]) and np.array_equal(rows,cols))

example1 = np.array(([2,7,6],[9,5,1],[4,3,8]))
example2 = np.array(([8,1,6],[3,5,7],[4,9,2]))
example3 = np.array(([8,1,2],[1,5,7],[4,9,2]))

print(magicsquare(example1))
print(magicsquare(example2))
print(magicsquare(example3))

Part D
True
True
False


## Question 2:


A) Plot a sine function in red with a dashed line
style, a cosin function in blue solid line, and the
legend. Then fill the area between the two
functions with yellow color if sine > cosine and
green color if cosine > sine. The x-limits are
between 0 and 10, whereas the y-limit is
between -1 and 1. (Hint: use plt.fill_between)


B) On a new figure plot a exp function in green,
add second y-axis (Hint, use plt.twinx) and plot
an exponential function on a y-logscale in red
(Hint, use plt.semilogy). Add a title, and labels
in fontsize 25 and in green and in red for
second y axis.