# Numpy Lessons

## Why numpy is faster than just lists

In [3]:
import numpy as np

R = range(1000)
%timeit [ i**2 for i in R ]

a = np.arange(1000)
%timeit  a**2 

575 µs ± 7.22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
2.79 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating Arrays

### Types of arrays you can create
side note: you can give numpy the dtype option to specify how to fill out the array. By default, arrays are created with float numbers. Type of arrays you can create:

* Manually filled values
  * np.array(([],[],...,[])) # where [] is a list or a single element. 
* Array filled with zeros
  * np.zeros((row,col))
* Array filled with ones
  * np.ones((row,col))
* Array with a range
  * np.arange(start, end, step) # step is optional
* Array with only the diagnogal being filled
  * np.diag(np.array([val1,val2,...,valn]))
* Array with with evenly spaced elements
  * np.linspace(start,end,elements in between)
* Array with all elements the same value
  * np.full((row,col),val)
* Identity Matrix
  * np.eye((4)) # 4 = number of cols and rows
* Empty Array
  * np.empty((2,3))
* Array with random values
  * np.random.random((row,col)) # all values will be between 0 and 1

In [11]:
print("#############################################")
print("Manually fill the Array")
sample = np.array(([1,2,3],[4,5,6]), dtype=np.float16)# 3D array, # dtype desired data type of array, optional
print(sample)

print("#############################################")
print("Array with all zeros")
sample = np.zeros((2,3))
print(sample)

print("#############################################")
print("Array with all ones")
sample = np.ones((2,3))
print(sample)

print("#############################################")
print("Array with a range")
sample = np.arange(2,20,2)
print(sample)

print("#############################################")
print("Array with only the diagnogal filled")
sample = np.diag(np.array([1,2,3,4]))
print(sample)

print("#############################################")
print("Evenly spaced elements")
sample = np.linspace(2,3,5)
print(sample)

print("#############################################")
print("All values the same")
sample = np.full((2,3),"ABC")
print(sample)


print("#############################################")
print("Identity Matrix")
sample = np.eye((3))
print(sample)

print("#############################################")
print("Empty Array")
sample = np.empty((2,3))
print(sample)

print("#############################################")
print("Array with random values")
sample = np.random.random((2,3))
print(sample)



#############################################
Manually fill the Array
[[1. 2. 3.]
 [4. 5. 6.]]
#############################################
Array with all zeros
[[0. 0. 0.]
 [0. 0. 0.]]
#############################################
Array with all ones
[[1. 1. 1.]
 [1. 1. 1.]]
#############################################
Array with a range
[ 2  4  6  8 10 12 14 16 18]
#############################################
Array with only the diagnogal filled
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
#############################################
Evenly spaced elements
[2.   2.25 2.5  2.75 3.  ]
#############################################
All values the same
[['ABC' 'ABC' 'ABC']
 ['ABC' 'ABC' 'ABC']]
#############################################
Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
#############################################
Empty Array
[[1. 1. 1.]
 [1. 1. 1.]]
#############################################
Array with random values
[[0.33315358 0.2275536  0.64622335]
 [0.57

### Class Example 1 

In [ ]:
a = np.array(([1,2,3],[4,5,6], [7,8,9]))

a[0,0]    # => 1
a[1,2]    # => 6
a[1,:]    # => array([4, 5, 6])  # : means all columns
a[1,1:2]  # => array([5])        # 1:2 means column 1
a[1,1:]   # => array([5, 6])     # 1: means from column 1 to end
a[:,1]    # => array([2, 5, 8])  # : means all rows
a[1:,1:2] # => array([[5],
          #           [8]])
a[::2,:]  # start:end:stepsize => array([[1, 2, 3],
          #                              [7, 8, 9]])
a[::-1,:] # start:end:-1 => reverse    => array([[7, 8, 9],
          #                                      [4, 5, 6],
          #                                      [1, 2, 3]])

### Class Example 2

In [6]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])    # 3 x 4 array
print("a.shape =", a.shape)
print("len(a) =", len(a))
print("a.ndim =", a.ndim)
print("a.size =", a.size)
print("a.dtype =", a.dtype)
print("a.itemsize =", a.itemsize)

a.shape = (3, 4)
len(a) = 3
a.ndim = 2
a.size = 12
a.dtype = int64
a.itemsize = 8


In [ ]:
### Other libraries built with numpy

SciPy # for more complex math problems (integrals, differential equations)
SymPy # for math symbols
statsmodels # for statistics
scikit-learn # Machine learning